/**
 * The in-game changelog data. One line per user-visible change merged to
 * main, newest first — written for the player ("what should I test?"),
 * not for developers (that's git log).
 *
 * PROCESS: every PR that merges a user-visible change appends its line
 * here in the same PR. Dates are merge dates.
 */

export interface ChangelogEntry {
  /** ISO date (YYYY-MM-DD) the change landed on main. */
  date: string;
  text: string;
}

export const CHANGELOG: ChangelogEntry[] = [
  { date: '2026-07-14', text: 'Tap-to-walk walks straight across open ground again — diagonal steps are saved for slipping around monsters and corners.' },
  { date: '2026-07-14', text: 'Tap-to-walk now takes diagonal shortcuts and can slip around a monster blocking your way.' },
  { date: '2026-07-14', text: 'Fixed ladders and stairwells you click to go up doing nothing — a single tap or click now climbs them.' },
  { date: '2026-07-14', text: 'Repeated door/walk warnings now expire instead of lingering, and duplicate spell speech echoes no longer stack twice.' },
  { date: '2026-07-14', text: 'Writable books and house guest, subowner, and door lists can now be edited and saved from their movable window.' },
  { date: '2026-07-14', text: 'Trading works: choose Trade with… on an item, tap a nearby player, then review and accept both offers.' },
  { date: '2026-07-14', text: 'Tap a creature on the map to select/attack it directly; red, gold, and white tap rings confirm attacks, uses, and walking.' },
  { date: '2026-07-14', text: 'Books, signs, and house access lists now open in a readable movable window instead of disappearing.' },
  { date: '2026-07-14', text: 'Settings, Hotkeys, Changelog, VIP, Skills, and container windows can be dragged by their headers and kept out of the action.' },
  { date: '2026-07-14', text: 'Panel, menu, and chat text is slightly smaller so more useful information fits on a phone.' },
  { date: '2026-07-14', text: 'Mobile view is no longer magnified by the phone’s pixel density, and portrait mode shows 11 tiles across instead of about six.' },
  { date: '2026-07-14', text: 'A single tap opens corpses and bags and uses doors, ladders, levers, and grates; Settings → Tap to walk can leave movement to the joystick.' },
  { date: '2026-07-14', text: 'Brightness now behaves like brightness: 0% is dark and 100% preserves the server’s full day/night light.' },
  { date: '2026-07-14', text: 'Server notices, look results, warnings, and status messages now appear briefly over the game as well as in chat.' },
  { date: '2026-07-14', text: 'Fixed looting the wrong item when a bag updated while its action sheet was open — the sheet now closes so you tap the live slot.' },
  { date: '2026-07-14', text: 'Fixed lower floors showing stale ghost tiles (or staying blank) when the ground above them changed, and fixed quickly opening two bags making the second replace the first.' },
  { date: '2026-07-14', text: 'Fixed the game opening zoomed-in/off-center after login when mobile Safari shifts the visible screen around the login form.' },
  { date: '2026-07-06', text: 'Torches and fires on other floors cast their light into your view.' },
  { date: '2026-07-06', text: 'People and monsters on other floors are visible now — watch them climb the stairs above you.' },
  { date: '2026-07-06', text: 'Buildings have roofs now — and they get out of the way when you step inside.' },
  { date: '2026-07-06', text: 'You can see down now: cliffs, holes and stairs show up to three floors below instead of black.' },
  { date: '2026-07-06', text: 'Fixed tapping stairs, ramps and holes doing nothing — tap them and you walk over and go up or down.' },
  { date: '2026-07-05', text: 'Use with works: pick a rope, shovel, or rune from a bag or your inventory, choose "Use with…", then tap the target — rope spots, stone piles, and enemies.' },
  { date: '2026-06-17', text: 'Damage numbers float up from hits and arrows/runes actually fly to their target.' },
  { date: '2026-06-17', text: 'Combat has visuals now: spell and hit effects play on the battlefield, and your attack target flashes a black square.' },
  { date: '2026-06-17', text: 'Looting works: tap an item in a corpse or bag to loot it to your backpack, look at it, or drop it — and tap equipment to unequip it into your backpack.' },
  { date: '2026-06-17', text: 'Dying shows a proper death screen with a Continue button instead of silently dumping you to the login form.' },
  { date: '2026-06-17', text: 'Opening a second bag no longer replaces the first window — containers open side by side.' },
  { date: '2026-06-17', text: 'Corpses and bags open now: double-tap a container to see its contents — tap an item to look at it, ⬆ goes back up, ✕ closes the window.' },
  { date: '2026-06-17', text: 'Walking into something impassable now stops instantly instead of stuttering against it.' },
  { date: '2026-06-11', text: 'Speech looks like Tibia now: yellow "Name says:" text above your head (orange for monsters), spam-casting stacks the lines upward, and longer texts stay longer.' },
  { date: '2026-06-11', text: 'Night is dark again: the world follows the server\'s day/night light, torches and fire fields glow, and your character carries their own light.' },
  { date: '2026-06-11', text: 'Settings → Brightness: 0% follows the server\'s darkness fully (classic Tibia), 100% ignores it — pick what your eyes want.' },
  { date: '2026-06-11', text: 'Dead creatures actually die now — they turn into their corpse instead of standing around with an empty health bar.' },
  { date: '2026-06-11', text: 'The menu pane scrolls now — entries past the bottom of the screen (VIP, Settings, Log out on small phones) are reachable again.' },
  { date: '2026-06-11', text: 'Spell buttons are bigger (thumb-sized) and the icons now fill the whole circle — tell us if the full-bleed look works.' },
  { date: '2026-06-11', text: 'The minimap moved to the left side under the health bar, and the 💬 chat bubble is gone (it sat on top of the spell buttons — chat lives in menu → Chat).' },
  { date: '2026-06-11', text: 'The spell buttons now fan out in a quarter-circle around the ⚔ attack button in the bottom-right corner (MOBA-style) — easier to reach with your thumb than the old vertical column.' },
  { date: '2026-06-11', text: 'Hotkeys got real: menu → Hotkeys now lists every castable spell on the server with official tibia.com icons — tap a slot to assign or swap, and the cast buttons show the spell images.' },
  { date: '2026-06-11', text: 'Fixed a crash at login when saved combat-mode settings were corrupted — invalid values now fall back to balanced/safe defaults.' },
  { date: '2026-06-11', text: 'Fixed the full black screen when opening the game over the network (plain http) — a diagnostics API only existed on https/localhost.' },
  { date: '2026-06-10', text: 'The UI component gallery (/ui-components.html) now covers all 19 components with up-to-date descriptions.' },
  { date: '2026-06-10', text: 'Added the VIP list (menu → VIP): see who is online, add and remove friends.' },
  { date: '2026-06-10', text: 'Spell slots are customizable (menu → Spells) and every known spell has an icon now.' },
  { date: '2026-06-10', text: 'Added the status bar: condition icons (poison, burn, haste, in-combat, …) appear under the health bar.' },
  { date: '2026-06-10', text: 'Added the battle list (menu → Battle): see every creature around you and tap one to attack it.' },
  { date: '2026-06-10', text: 'The Skills pane now shows everything: level with a red progress bar, experience, magic level, capacity, and soul.' },
  { date: '2026-06-10', text: 'Added combat modes (right edge): attack/balanced/defense stance, chase, and secure/PK toggle — remembered between sessions.' },
  { date: '2026-06-10', text: 'Added a full-screen chat (menu → Chat) — same channels and history as the bottom panel.' },
  { date: '2026-06-10', text: 'Added the minimap (top-right) — real automap colors, toggle it in Settings.' },
  { date: '2026-06-10', text: 'Fixed the game loading zoomed-in/off-center (you only saw the tiles north of you) — the screen now re-measures itself after iOS settles.' },
  { date: '2026-06-10', text: 'Walking rebuilt on game-netcode patterns: a small playback delay absorbs Wi-Fi hiccups, and steps are pre-queued on the server — waves of good/bad smoothness should be gone.' },
  { date: '2026-06-10', text: 'Dev builds stream walk/render telemetry to the proxy so lag reports come with data (?telemetry=0 opts out).' },
  { date: '2026-06-10', text: 'Fixed heavy stutter around houses/towns — the map no longer redraws everything 8× a second while walking.' },
  { date: '2026-06-10', text: 'Walking flows through network hiccups (no more stutter every few tiles) and the black edge behind you while moving is gone.' },
  { date: '2026-06-10', text: 'Continuous walking: steps now glide at your real walking rhythm — no more micro-pause between tiles.' },
  { date: '2026-06-10', text: 'Walking is smooth now: the camera and creatures glide between tiles instead of snapping.' },
  { date: '2026-06-10', text: 'The screen no longer dims/sleeps while playing (wake lock, like the offline map).' },
  { date: '2026-06-10', text: 'Tap-to-walk is back: tap a tile and the player paths to it (long-press still looks, double-tap still uses).' },
  { date: '2026-06-10', text: 'The inventory now shows real item graphics instead of numbers.' },
  { date: '2026-06-10', text: 'New look: the purple is gone — the UI is now blacks, grays, and whites.' },
  { date: '2026-06-10', text: 'Settings → Show metrics: on-screen FPS, walk latency, and repaint cost for the lag hunt (?metrics=1 works too).' },
  { date: '2026-06-10', text: 'Added Settings to the menu — auto-attack toggle, synced with the ⚔ circle.' },
  { date: '2026-06-10', text: 'Fixed monsters not visibly walking (their steps were being dropped).' },
  { date: '2026-06-10', text: 'Rats now spawn just east of the D\'aracia depot for combat testing.' },
  { date: '2026-06-10', text: 'Added this changelog to the menu — check here to see what to test.' },
  { date: '2026-06-10', text: 'Fixed stairs/ladders putting you in the wrong place with black areas around you.' },
  { date: '2026-06-10', text: 'Fixed your name vanishing after going down a floor.' },
  { date: '2026-06-10', text: 'Chat is now a fixed small panel with a ✕ to close it; switching channels no longer resizes or breaks it.' },
  { date: '2026-06-10', text: 'Fixed the player (and creatures) always facing the same way while walking.' },
  { date: '2026-06-10', text: 'Dev builds auto-login on reload (add ?autologin=0 to use the form).' },
  { date: '2026-06-10', text: 'The game now fills the whole phone screen in both orientations — no more purple bars.' },
  { date: '2026-06-10', text: 'Fixed iOS staying zoomed-in after the first login (input focus auto-zoom).' },
  { date: '2026-06-10', text: 'Added the combat bar: spell circles (exura, vita, lux) and a ⚔ auto-attack toggle that sticks to its target.' },
  { date: '2026-06-10', text: 'Added speech bubbles above creatures when they talk.' },
  { date: '2026-06-10', text: 'Added look (long-press / right-click), use (double-tap — ladders, sewers, doors), and Log out in the menu.' },
  { date: '2026-06-10', text: 'Added the inventory pane — live equipment, toggled from the menu.' },
  { date: '2026-06-09', text: 'Walk animation: creatures cycle walk poses on confirmed steps.' },
  { date: '2026-06-09', text: 'Landing page at / — Play online or Browse the map.' },
  { date: '2026-06-09', text: 'Fixed citizen outfit colors to match the real server defaults.' },
];
